name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  ELASTIC_BEANSTALK_NAME: tetatet-backend
  ELASTIC_BEANSTALK_ENV_NAME: Tetatet-backend-env

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - uses: actions/checkout@master
    
    - name: Copy and rename file
      run: cp Teta/appsettings.Example.json Teta/appsettings.json
      
    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      continue-on-error: true
      with:
        files: 'Teta/appsettings.json'
      env:
        ConnectionStrings.Default: ${{ secrets.DB_CONNECTION }}
        Jwt.Secret: ${{ secrets.JWT_SECRET }}
        Amazon.S3.AccessKey: ${{ secrets.AWS_ACCESS_KEY_ID }}
        Amazon.S3.SecretKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        Amazon.S3.BucketName: 'tetatet-images'
        Stripe.SecretKey: ${{ secrets.STRIPE_SECRET_KEY }}
        Stripe.PublishableKey: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
        Stripe.WebHookSecret: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
        Stripe.SuccessUrl: 'https://tete-a-tete.network/en'
        Stripe.CancelUrl: 'https://tete-a-tete.network/en'
        SendGrid.ApiKey: ${{ secrets.SENDGRID_API_KEY }}
        SendGrid.FromEmail: 'notifications@tetatet.network'
        SendGrid.FromName: 'Tetatet App'
        EmailRestoreLink: 'https://tete-a-tete.network/handle-forgot-password'
        Domains.Client: 'https://tete-a-tete.network'
        Authentication.Google.Id: ${{ secrets.GOOGLE_ID }}
        Authentication.Google.Secret: ${{ secrets.GOOGLE_SECRET }}

    - name: Apply EF Core Migrations
      run: |
        cd Teta
        dotnet tool install --global dotnet-ef
        dotnet tool restore
        dotnet ef database update
      continue-on-error: true
  
    - name: Publish prod
      run: cd Teta; dotnet restore; dotnet publish -r win-x64 --configuration "Release" --self-contained "true" -o ../site;

    - name: Generate deployment package 
      run: cd site; zip ../site.zip *; cd ..; zip ${{github.run_id}}.zip site.zip aws-windows-deployment-manifest.json
      
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v22
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ${{ env.ELASTIC_BEANSTALK_NAME }}
        environment_name: ${{ env.ELASTIC_BEANSTALK_ENV_NAME }}
        version_label: ${{ github.run_id }}
        region: us-west-1
        deployment_package: ${{github.run_id}}.zip
